services:
  web:
    build: ./
    ports:
      - "8080:8080"
    environment:
      APP: "web"
      PORT: "8080"
      APP1_URL: "http://app1:3001/"
      APP2_URL: "http://app2:3002/"
      APP3_URL: "http://app3:3003/"

  app1:
    image: "mbigras/app"
    ports:
      - "3001:3001"
    environment:
      APP: "app1"
      PORT: "3001"
      ENV: "dev"

  app2:
    image: "mbigras/app"
    ports:
      - "3002:3002"
    environment:
      APP: "app2"
      PORT: "3002"
      ENV: "dev"

  app3:
    image: "mbigras/app"
    ports:
      - "3003:3003"
    environment:
      APP: "app3"
      PORT: "3003"
      ENV: "dev"
